openapi: 3.1.0
info:
  version: next
  title: NHS Notify Supplier API
  description: |
    API for communication suppliers to integrate with NHS Notify.

    This specification represents the in-development 'next' version of the API schema
    and should be treated as unstable.
security:
  - authorization: [ ]
paths:
  /batch:
    parameters:
      - $ref: '#/components/parameters/requestId'
      - $ref: '#/components/parameters/correlationId'
    get:
      summary: Retrieve a list of available letter batches
      operationId: get-batches
      tags:
        - batch
      responses:
        '200':
          description: OK
          content:
            application/vnd.api+json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    links:
                      self: 'http://example.com/batches'
                      first: 'http://example.com/batches?cursor='
                      last: 'http://example.com/batches?cursor=-1'
                      prev: 'http://example.com/batches?cursor='
                      next: 'http://example.com/batches?cursor=2WL5eYSWGzCHlGmzNxuqVusPxDg'
                    data:
                      - type: batches
                        id: 2WL5eYSWGzCHlGmzNxuqVusPxDg
                        attributes: { }
                      - type: batches
                        id: 2WL5f8j4XVxUPgd3OOqXVYvVIOP
                        attributes: { }
                properties:
                  links:
                    type: object
                    required:
                      - self
                      - first
                      - last
                    properties:
                      self:
                        type: string
                      first:
                        type: string
                      last:
                        type: string
                      prev:
                        type: string
                      next:
                        type: string
                  data:
                    type: array
                    items:
                      type: object
                      required:
                        - type
                        - id
                      properties:
                        type:
                          type: string
                          const: Batch
                        id:
                          type: string
                          description: 'ID of a batch which can be fetched from the /batch/{id} endpoint'
              examples:
                Example 1:
                  value:
                    links:
                      self: 'http://example.com/batches'
                      first: 'http://example.com/batches?cursor='
                      last: 'http://example.com/batches?cursor=-1'
                      prev: 'http://example.com/batches?cursor='
                      next: 'http://example.com/batches?cursor=2WL5eYSWGzCHlGmzNxuqVusPxDg'
                    data:
                      - type: batches
                        id: 2WL5eYSWGzCHlGmzNxuqVusPxDg
                      - type: batches
                        id: 2WL5f8j4XVxUPgd3OOqXVYvVIOP
  '/batch/{id}':
    parameters:
      - $ref: '#/components/parameters/requestId'
      - $ref: '#/components/parameters/correlationId'
      - $ref: '#/components/parameters/id'
    get:
      summary: Retrieve a batch of letters
      description: Get details about a batch of letters
      operationId: get-batch-id
      responses:
        '200':
          description: Batch of letters found
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/BatchResponse'
              examples:
                Pre-rendered:
                  value:
                    data:
                      type: Letters
                      id: 2WL5eYSWGzCHlGmzNxuqVusPxDg
                      attributes:
                        prerendered: true
                        download:
                          url: 'http://s3-presigned-url'
                          expiry: '2024-11-09T10:31:59Z'
                          sha256: 9bf1619f5c5d60f18c14578994b6310ee3339f435b6b6424fde1bb7d91b5ab71
                          signature: d034c98af3274ad93f3c8ce944bbc17b11b6aa170c5f097ed98687fa0d93347c
                          key: c374556584db050001c2c9265b546e66d3dbbe8239d17427c176d834a19638dc
                        prerenderedLetters:
                          - messageId: 2WL5f8j4XVxUPgd3OOqXVYvVFIW
                            fileName: 2WL5f8j4XVxUPgd3OOqXVYvVFIW.pdf
                            sha256: 640a0675231ae4b001f1f8e4699a19e806aef0504b4556a0b9b644d141316a33
                          - messageId: 2WL5f8j4XVxUPgd3OOqXVYvVIOP
                            fileName: 2WL5f8j4XVxUPgd3OOqXVYvVIOP.pdf
                            sha256: 51b8feebfce64e709196a517340ffd0359c517b9a89084430e6b90cf3bdacc7a
                Personalised:
                  value:
                    data:
                      type: Letters
                      id: 2WL5eYSWGzCHlGmzNxuqVusPxDg
                      attributes:
                        prerendered: false
                        personalisedLetters:
                          - messageId: 2WL5f8j4XVxUPgd3OOqXVYvVFIW
                            personalisation:
                              address_line_1: Mr John Smith
                              date: 20th May 2025
                              time: '10:30am'
                          - messageId: 2WL5f8j4XVxUPgd3OOqXVYvVIOP
                            personalisation:
                              address_line_1: Ms Jane Doe
                              date: 20th May 2025
                              time: '10:30am'
        '404':
          $ref: '#/components/responses/ResourceNotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
      tags:
        - batch
      parameters:
        - $ref: '#/components/parameters/id'
    patch:
      summary: Update the status of a batch of letters
      description: Update the status of a batch of letters by providing the new status in the request body.
      operationId: patch-letters-batch
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/BatchUpdateRequest'
      responses:
        '200':
          description: Letters resources updated successfully
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/BatchUpdateResponse'
              examples:
                example-1:
                  value:
                    data:
                      type: Letter
                      id: 2WL5f8j4XVxUPgd3OOqXVYvVFIW
                      attributes:
                        status: ACCEPTED
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/ResourceNotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
      tags:
        - batch
      parameters:
        - $ref: '#/components/parameters/id'
  /letter:
    parameters:
      - $ref: '#/components/parameters/requestId'
      - $ref: '#/components/parameters/correlationId'
    post:
      summary: Update the status of multiple letters
      operationId: postLetter
      tags:
        - letter
    get:
      summary: Get a list of letters
      operationId: getAListOfLetters
      tags:
        - letter
      parameters:
        - $ref: '#/components/parameters/status'
      description: The key use of this endpoint is to query letters which have been cancelled using the `status=CANCELLED` query
  '/letter/{id}':
    parameters:
      - $ref: '#/components/parameters/requestId'
      - $ref: '#/components/parameters/correlationId'
      - $ref: '#/components/parameters/id'
    get:
      summary: Retrieve the status of a letter
      description: Get details the status of a letter.
      operationId: get-letter-status
      responses:
        '200':
          description: Letter status
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/LetterStatusResponse'
              examples:
                example-1:
                  value:
                    data:
                      type: Letter
                      id: 2WL5f8j4XVxUPgd3OOqXVYvVFIW
                      attributes:
                        status: ACCEPTED
        '404':
          $ref: '#/components/responses/ResourceNotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
      tags:
        - letter
    patch:
      summary: Update the status of a letter
      description: Update the status of a letter by providing the new status in the request body.
      operationId: patch-letters
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/LetterUpdateRequest'
      responses:
        '200':
          description: Letter resource updated successfully
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/LetterStatusResponse'
              examples:
                example-1:
                  value:
                    data:
                      type: Letter
                      id: 2WL5f8j4XVxUPgd3OOqXVYvVFIW
                      attributes:
                        status: ACCEPTED
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/ResourceNotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/ServerError'
      tags:
        - letter
  /mi:
    parameters:
      - $ref: '#/components/parameters/requestId'
      - $ref: '#/components/parameters/correlationId'
    get:
      summary: List MI records
      operationId: list-mi
      tags:
        - mi
    post:
      summary: Create a new MI record
      operationId: create-mi
      tags:
        - mi
  '/mi/{id}':
    parameters:
      - $ref: '#/components/parameters/requestId'
      - $ref: '#/components/parameters/correlationId'
      - $ref: '#/components/parameters/id'
    get:
      summary: Fetch a specific MI record
      operationId: get-mi
      tags:
        - mi
  /specification:
    parameters:
      - $ref: '#/components/parameters/requestId'
      - $ref: '#/components/parameters/correlationId'
    get:
      summary: List specifications
      operationId: list-specification
      tags:
        - specification
    post:
      summary: Create a new specification record
      operationId: create-specification
      tags:
        - specification
  '/specification/{id}':
    parameters:
      - $ref: '#/components/parameters/requestId'
      - $ref: '#/components/parameters/correlationId'
      - $ref: '#/components/parameters/id'
    get:
      summary: Fetch metadata about a specific specification
      operationId: get-specification
      tags:
        - specification
    patch:
      summary: Update metadata about a specific specification
      operationId: patch-specification
      tags:
        - specification
  /proof:
    parameters:
      - $ref: '#/components/parameters/requestId'
      - $ref: '#/components/parameters/correlationId'
    get:
      summary: List proof files
      operationId: list-proof
      tags:
        - proof
    post:
      summary: Create a new proof metadata record
      operationId: create-proof
      tags:
        - proof
  '/proof/{id}':
    parameters:
      - $ref: '#/components/parameters/requestId'
      - $ref: '#/components/parameters/correlationId'
      - $ref: '#/components/parameters/id'
    get:
      summary: Fetch metadata about a specific proof file
      operationId: get-proof
      tags:
        - proof
    patch:
      summary: Update metadata about a specific proof file
      operationId: patch-proof
      tags:
        - proof
  /artwork:
    parameters:
      - $ref: '#/components/parameters/requestId'
      - $ref: '#/components/parameters/correlationId'
    post:
      summary: Create a new artwork metadata record
      operationId: create-artwork
      tags:
        - artwork
    get:
      summary: List artwork files
      operationId: list-artwork
      tags:
        - artwork
  '/artwork/{id}':
    parameters:
      - $ref: '#/components/parameters/requestId'
      - $ref: '#/components/parameters/correlationId'
      - $ref: '#/components/parameters/id'
    get:
      summary: Fetch metadata about a specific artwork file
      operationId: get-artwork
      tags:
        - artwork
    patch:
      summary: Update metadata about a specific artwork file
      operationId: patch-artwork
      tags:
        - artwork
  /whitemail:
    parameters:
      - $ref: '#/components/parameters/requestId'
      - $ref: '#/components/parameters/correlationId'
    get:
      summary: List batches of whitemail letters
      operationId: list-whitemail
      tags:
        - whitemail
      x-stoplight:
        id: tpzuuj1eovmtc
    post:
      summary: Create a new whitemail letter batch
      operationId: create-whitemail
      tags:
        - whitemail
      x-stoplight:
        id: wun7ud7savffm
  '/whitemail/{id}':
    parameters:
      - $ref: '#/components/parameters/requestId'
      - $ref: '#/components/parameters/correlationId'
      - $ref: '#/components/parameters/id'
    get:
      summary: Fetch metadata about a specific whitemail batch
      operationId: get-whitemail
      tags:
        - whitemail
      x-stoplight:
        id: lmbg85kro8iwy
  /data:
    parameters:
      - $ref: '#/components/parameters/requestId'
      - $ref: '#/components/parameters/correlationId'
    post:
      summary: Request a URL to upload a new data file
      operationId: post-data
      tags:
        - data
  '/data/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
      - name: id
        in: path
        description: Unique identifier of this resource
        required: true
        schema:
          type: string
      - name: X-Request-ID
        in: header
        description: 'Unique request identifier, in the format of a GUID'
        required: true
        schema:
          type: string
          examples:
            - dcb9c8dc-c2f4-4d5f-8674-a2e913e040b2
      - name: X-Correlation-ID
        in: header
        description: |-
          An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
          The ID will be returned in a response header.
        required: false
        schema:
          type: string
          examples:
            - 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
    get:
      summary: Fetch a data file
      operationId: get-data-id
      tags:
        - data
      x-stoplight:
        id: 98lwlebl1vxeq
      responses:
        '303':
          description: See Other
          headers:
            Location:
              schema:
                type: string
              description: The signed S3 URL of the data file to download
    head:
      summary: Fetch data file metadata
      tags:
        - data
      responses: {}
      operationId: head-data-id
      x-stoplight:
        id: tdjs72iaaavub
components:
  parameters:
    requestId:
      name: X-Request-ID
      in: header
      description: 'Unique request identifier, in the format of a GUID'
      required: true
      schema:
        type: string
        examples:
          - dcb9c8dc-c2f4-4d5f-8674-a2e913e040b2
    correlationId:
      name: X-Correlation-ID
      in: header
      description: |-
        An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters. If not provided in the request, NHS Notify will default to a system generated ID in its place.
        The ID will be returned in a response header.
      required: false
      schema:
        type: string
        examples:
          - 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
    id:
      name: id
      in: path
      description: Unique identifier of this resource
      required: true
      schema:
        type: string
    status:
      name: status
      in: query
      description: Status of a letter
      required: true
      schema:
        $ref: '#/components/schemas/LetterStatus'
  securitySchemes:
    authorization:
      type: oauth2
      description: |-
        An [OAuth 2.0 bearer token](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/application-restricted-restful-apis-signed-jwt-authentication).
        Required in all environments except local and sandbox.
      flows:
        authorizationCode:
          authorizationUrl: ''
          tokenUrl: ''
  schemas:
    DataReference:
      type: object
      x-stoplight:
        id: 7fd8f6f57a5a2
      required:
        - id
        - sha256
        - signature
        - key
      properties:
        id:
          type: string
          description: 'ID of a data file which can be requested from the /data/{id} endpoint'
        sha256:
          $ref: '#/components/schemas/Sha256'
        signature:
          $ref: '#/components/schemas/EcdsaSignature'
        key:
          $ref: '#/components/schemas/EcdsaKey'
    Letter:
      type: object
      x-stoplight:
        id: 7gylnxnf8h4w3
      required:
        - messageId
        - fileName
        - sha256
      properties:
        messageId:
          type: string
          examples:
            - 2WL5f8j4XVxUPgd3OOqXVYvVFIW
        fileName:
          type: string
          examples:
            - 2WL5f8j4XVxUPgd3OOqXVYvVFIW.pdf
        sha256:
          $ref: '#/components/schemas/Sha256'
    ErrorResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/ErrorData'
    ErrorData:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorItem'
    ErrorItem:
      type: object
      properties:
        id:
          type: string
        code:
          type: string
          enum:
            - NOTIFY_NO_BATCH_AVAILABLE
            - NOTIFY_INTERNAL_SERVER_ERROR
            - NOTIFY_INVALID_REQUEST
            - NOTIFY_LETTER_NOT_FOUND
        links:
          type: object
          properties:
            about:
              type: string
              format: uri
        status:
          type: string
        title:
          type: string
        detail:
          type: string
    BatchUpdateRequest:
      $ref: '#/components/schemas/BatchUpdateData'
      x-stoplight:
        id: 9c08a5637342c
    BatchUpdateData:
      type: object
      x-stoplight:
        id: 437c50381c0c6
      properties:
        data:
          type: object
          properties:
            type:
              const: Batch
            id:
              type: string
              examples:
                - 2WL5eYSWGzCHlGmzNxuqVusPxDg
            attributes:
              type: object
              properties:
                status:
                  $ref: '#/components/schemas/BatchStatus'
                  description: New status to be applied to the batch of letters
                reasonCode:
                  type: number
                  description: Reason code for the given status
                  examples:
                    - 100
                reasonText:
                  type: string
                  description: Reason text for the given status
                  examples:
                    - failed validation
    BatchUpdateResponse:
      $ref: '#/components/schemas/BatchUpdateData'
      x-stoplight:
        id: 973aca4e625e6
    LetterUpdateRequest:
      $ref: '#/components/schemas/LetterUpdateData'
    LetterUpdateData:
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              type: string
              const: Letter
            id:
              type: string
              examples:
                - 2WL5eYSWGzCHlGmzNxuqVusPxDg
            attributes:
              type: object
              properties:
                status:
                  $ref: '#/components/schemas/LetterStatus'
                requestedProductionStatus:
                  $ref: '#/components/schemas/ProductionStatus'
                  x-stoplight:
                    id: tqw1mlpdzl3v7
                  description: |-
                    The requested production status for this letter.
                    May only be set by NHS Notify.
                reasonCode:
                  type: number
                  description: Reason code for the given status
                  examples:
                    - 100
                reasonText:
                  type: string
                  description: Reason text for the given status
                  examples:
                    - failed validation
    LetterStatusData:
      type: object
      properties:
        data:
          type: object
          properties:
            type:
              type: string
              const: Letter
            id:
              type: string
              examples:
                - 2WL5eYSWGzCHlGmzNxuqVusPxDg
            attributes:
              type: object
              required:
                - status
                - requestedProductionStatus
              properties:
                status:
                  $ref: '#/components/schemas/LetterStatus'
                requestedProductionStatus:
                  $ref: '#/components/schemas/ProductionStatus'
                  x-stoplight:
                    id: kqs13rn7s4wv3
                reasonCode:
                  type: number
                  description: Reason code for the given status
                  examples:
                    - 100
                reasonText:
                  type: string
                  description: Reason text for the given status
                  examples:
                    - failed validation
    LetterStatus:
      type: string
      enum:
        - PENDING
        - ACCEPTED
        - REJECTED
        - PRINTED
        - ENCLOSED
        - CANCELLED
        - DISPATCHED
        - FAILED
        - RETURNED
        - DESTROYED
        - FORWARDED
      description: The supplier status of an individual letter
      examples:
        - PENDING
      default: PENDING
    BatchStatus:
      type: string
      x-stoplight:
        id: nv131u406b1lq
      enum:
        - PENDING
        - ACCEPTED
        - REJECTED
        - CANCELLED
      description: The supplier status of a batch of letters
      examples:
        - PENDING
      default: PENDING
    LetterStatusResponse:
      $ref: '#/components/schemas/LetterStatusData'
    ProductionStatus:
      type: string
      x-stoplight:
        id: lvub504h38th0
      enum:
        - ACTIVE
        - HOLD
        - CANCEL
      description: A requested status for the production of a letter
      examples:
        - ACTIVE
      title: ProductionStatus
    BatchResponse:
      type: object
      x-stoplight:
        id: e6650543dba07
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - id
            - attributes
          properties:
            type:
              type: string
              const: Batch
            id:
              type: string
              examples:
                - 2WL5eYSWGzCHlGmzNxuqVusPxDg
            attributes:
              $ref: '#/components/schemas/Batch'
    Sha256:
      title: Sha256
      x-stoplight:
        id: ul241al5tpyrm
      type: string
      examples:
        - 9bf1619f5c5d60f18c14578994b6310ee3339f435b6b6424fde1bb7d91b5ab71
      description: SHA 256 Hash of a file or other resource used to verify the expected content
    EcdsaKey:
      title: EcdsaKey
      type: string
      examples:
        - c374556584db050001c2c9265b546e66d3dbbe8239d17427c176d834a19638dc
      description: Public ECDSA Key corresponding to a signature used to verify the originator of a file. This public key should correspond to one published by NHS Notify.
    EcdsaSignature:
      title: EcdsaSignature
      x-stoplight:
        id: y4t72k7ltybkm
      type: string
      examples:
        - d034c98af3274ad93f3c8ce944bbc17b11b6aa170c5f097ed98687fa0d93347c
      description: ECDSA Signature of a file or other resource used to verify the originator
    Batch:
      title: Batch
      x-stoplight:
        id: np2gpu3lt30rm
      type: object
      required:
        - status
        - download
        - letters
      properties:
        status:
          $ref: '#/components/schemas/BatchStatus'
          x-stoplight:
            id: 9j074tvulfns6
        data:
          $ref: '#/components/schemas/DataReference'
        letters:
          type: array
          items:
            $ref: '#/components/schemas/Letter'
            x-stoplight:
              id: 1s1ff8b7cjr9q
        reasonCode:
          type: number
          x-stoplight:
            id: 88vy6s9fc5his
        reasonText:
          type: string
          x-stoplight:
            id: 166lb0fs8wz2r
  responses:
    BadRequest:
      description: 'Bad request, invalid input data'
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            error-1:
              value:
                errors:
                  - id: rrt-1931948104716186917-c-geu2-10664-3111479-3.0
                    code: NOTIFY_INVALID_REQUEST
                    links:
                      about: 'https://digital.nhs.uk/developer/api-catalogue/nhs-notify'
                    status: '400'
                    title: Invalid request
                    detail: 'Invalid request, please refer to the API specifications'
    ResourceNotFound:
      description: Resource not found
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            error-1:
              value:
                errors:
                  - id: rrt-1931948104716186917-c-geu2-10664-3111479-3.0
                    code: NOTIFY_RESOURCE_NOT_FOUND
                    links:
                      about: 'https://digital.nhs.uk/developer/api-catalogue/nhs-notify'
                    status: '404'
                    title: Resource not found
                    detail: No resource found with that ID
    TooManyRequests:
      description: Too many requests
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            error-1:
              value:
                errors:
                  - id: rrt-1931948104716186917-c-geu2-10664-3111479-3.0
                    code: NOTIFY_QUOTA
                    links:
                      about: 'https://digital.nhs.uk/developer/api-catalogue/nhs-notify'
                    status: '429'
                    title: Too many requests
                    detail: You have made too many requests. Please try again later.
    ServerError:
      description: Server error
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            error-1:
              value:
                errors:
                  - id: rrt-1931948104716186917-c-geu2-10664-3111479-3.0
                    code: NOTIFY_INTERNAL_SERVER_ERROR
                    links:
                      about: 'https://digital.nhs.uk/developer/api-catalogue/nhs-notify'
                    status: '500'
                    title: Internal Server Error
                    detail: 'An unexpected error occurred, please contact support'
tags:
  - name: letter
    description: ''
  - name: batch
    description: ''
  - name: specification
    description: ''
  - name: whitemail
    description: ''
  - name: proof
    description: ''
  - name: mi
    description: ''
  - name: artwork
    description: ''
  - name: data
    description: ''
servers:
  - url: 'http://127.0.0.1:3000'
    description: Local development server
  - url: 'https://sandbox-server.nhs.uk/nhs-notify-supplier-api'
    description: Public sandbox
